from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add
from utils import llmpick

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="List of Message to be processed")
    user_ques : str = Field(..., description="User question to be processed by the agent")
    curated_ques : str = Field(..., description="Curated user question")
    prompt_query_context: str = Field(..., description="Detaild prompt with SQL DB context that will help agent to generate SQL Query")
    is_safe: Literal["Yes","No"] = Field(..., description="Indicates wheather the generated SQL query is safe")
    generated_sql_query : str = Field(..., description="The SQL Query generated by the agent")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL Query")
    final_response : str = Field(..., description="The final response the agent based on the SQL Queryresponse")

# LLM AS JUDGE

class JudgeSchema(BaseModel):
    answer: Literal["Yes","No"] = Field(..., description="Indicates wheather the generated SQL query is safe to execute or not")
    comments: str = Field(...,description="Additional comments or feedback from the judge regarding SQL query")